name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [9] # Version of GFortran we want to use.
    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test TOML syntax
      run: |
        python load_registry.py

    - name: Check index
      if: ${{ github.event_name == 'pull_request' }}
      run: python build_index.py --check-new

    - name: Build index
      if: ${{ github.event_name == 'push' }}
      run: python build_index.py --check-all

    - name: Commit updated index
      if: ${{ github.event_name == 'push' }}
      uses: EndBug/add-and-commit@v4.4.0
      with:
        add: index.json
        message: "Rebuild index.json, commit ${{github.sha}} (on:push)"
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
